### ISSUE TITLE
the Chinese characters of bookmark outlines are garbled

### ISSUE THREAD

**Issue by Guoozz** [jung-kurt/gofpdf#307] opened 2019-09-25 06:28 UTC
I want to generate PDF that contains bookmark outlines, but the Chinese characters are corrupted.

##  Test Code

```go
func ExampleFpdf_Bookmark() {
	pdf := gofpdf.New("P", "mm", "A5", "")
	pdf.AddUTF8Font("SourceHanSerif", "", "SourceHanSerifCN-ExtraLight.ttf")
	pdf.SetFont("SourceHanSerif", "", 16)
	pdf.AddPage()
	pdf.Bookmark("目录1", 0, 0)
	pdf.Bookmark("子目录1", 1, -1)
	pdf.Cell(0, 6, "段落 1")
	pdf.Ln(50)
	pdf.Bookmark("目录2", 1, -1)
	pdf.Cell(0, 6, "段落 2")
	pdf.AddPage()
	pdf.Bookmark("目录3", 0, 0)
	pdf.Bookmark("Paragraph 3", 1, -1)
	pdf.Cell(0, 6, "Paragraph 3")
	fileStr := example.Filename("Fpdf_Bookmark")
	err := pdf.OutputFileAndClose(fileStr)
	example.Summary(err, fileStr)
	// Output:
	// Successfully generated pdf/Fpdf_Bookmark.pdf
}
```

## Generated PDF
![image](https://user-images.githubusercontent.com/8208557/65574672-a820e400-dfa0-11e9-9b25-9e750f1d7198.png)

**Comment by jung-kurt** [comment] 2019-09-25 12:27
Thanks for the report, @Guoozz. If I remember correctly, those bookmark names are UTF-16 encoded. I don't think the recent UTF-8 work included any conversion routines to UTF-16. I will look into this and hope others do too.

**Comment by devplayg** [comment] 2019-09-26 00:28
The same problem occurs when entering Korean bookmarks.

```
func (r *Report) writeReport(pdf *gofpdf.Fpdf) error {
    pdf.AddPage()
    pdf.SetFont(HangulFont, "", 16)
    pdf.Bookmark(Lang("report.cover"), 0, 0)
    pdf.Cell(0, 6, "1. 커버")
```

**Comment by SuddenGunter** [comment] 2019-09-26 19:04
@jung-kurt can I take it, is this a good first issue?
I've not so much experience in Go

**Comment by jung-kurt** [comment] 2019-09-27 00:22
> can I take it

Absolutely! Thanks or your interest, @SuddenGunter!

> is this a good first issue?

Possibly -- I haven't looked into to know how difficult it might be. You will want to study `utf8toutf16()` and `.isCurrentUTF8`. My assumption here is that the bookmark problem occurs only with UTF-8 fonts.

If this problem turns out to be too frustrating but you are still interested in tackling something else, let me know and I'll scan the list for another issue.

**Comment by SuddenGunter** [comment] 2019-09-28 21:25
I was able to reproduce it locally. It took some time to install Chinese fonts and get it to work.
Will debug it and try to fix, possibly this weekend

**Comment by jung-kurt** [comment] 2019-09-28 23:49
@SuddenGunter: Thanks for your work on this and for your updates!

**Comment by SuddenGunter** [comment] 2019-09-29 00:22
@Guoozz @devplayg plz check latest version: was issue resolved for you?

**Comment by Guoozz** [comment] 2019-09-29 00:43
@SuddenGunter the problem has resolved, thanks very much.

**Comment by SuddenGunter** [comment] 2019-09-29 21:23
@jung-kurt can we close this issue now?

**Comment by jung-kurt** [comment] 2019-09-29 22:59
> can we close this issue now?

Yes, you may have the honors. Thanks again, @SuddenGunter.

**Comment by SuddenGunter** [comment] 2019-10-09 09:25
>Yes, you may have the honors
but I don't have required rights in repo :)
do it

**Closed** 2019-10-09 10:57 UTC
Labels: bug, help wanted
