### ISSUE TITLE
Testing: add file comparison.

### ISSUE THREAD

**Issue by jelmersnoeck** [jung-kurt/gofpdf#46] opened 2015-10-04 18:54 UTC
At the moment, the tests validate that the code runs. It also provides a lot of examples for the users of gofpdf.

However, it doesn't test if functionality is as expected. This is particularly important when changing functionality or adding new features.

My suggestion for this would be to have a set of pre-defined PDFs (the ones that are generated through the examples now) and compare the same PDF generation instructions to those PDFs. This assures that new/changed code wouldn't change old output (unintentional).

To do this, there needs to be a change to the way the file gets parsed. At the moment, `time.Now()` is used to put the creation date in place. This makes it tricky to compare the file as this date always changes and thus the output will always be different.

I'm suggesting a simple Clock implementation here to make it possible to mock this out during tests.

I have made a rough version of how this could work here: https://github.com/jung-kurt/gofpdf/compare/master...jelmersnoeck:test-comparison?expand=1

Would you be open to accept this kind of system for testing output? (Note, the version above is a POC, the actual implementation will probably be a bit different)

**Comment by jung-kurt** [comment] 2015-10-04 19:21
Excellent solution to a real problem. This will definitely be accepted into the project.

We could either have a set of pre-generated PDFs with which the test results can be compared, or maintain a hash of each file and compare those values.

I have been reluctant to include PDFs in the repository because their internal time fields would result in a lot of commit noise or cumbersome workarounds. But since your solution removes this variability, we may want to consider including PDFs not only for test comparisons but as samples for people investigating the project. Links could be provided from the README.

**Comment by marcusatbang** [comment] 2015-10-04 20:45
Is it certain that there are no non-deterministic elements in the PDF syntax? Given the nature of the format, it's very easy for two files to look identical but be written differently. For example, might Windows and Linux calculate font weights differently and so break strings directly?

If this question has a satisfactory answer, this sounds like a good solution.

As neat as it would be to compare file hashes, keeping the PDFs gives you the chance to compare diff and see what's changed, which would be useful for debugging.

**Comment by jung-kurt** [comment] 2015-10-04 21:02
Good points, @marcusatbang. We also need to consider changes between versions of the compiler and standard library. For example, images could be constructed with slightly different internal values.

**Comment by marcusatbang** [comment] 2015-10-04 21:05
This can probably be answered by testing rather than guessing. @jung-kurt, do you want to check in some standard tests and I'll see what I get on Windows?

Unless there's since way of testing if two files are _equivalent_, rather than equal?

**Comment by jelmersnoeck** [comment] 2015-10-04 21:43
@marcusatbang That is a very good point. I am actually running some more tests and seeing some failures on comparison. I will dig into it more and see what the issue is an if this is solvable.

**Comment by marcusatbang** [comment] 2015-10-07 23:43
I've thought about this some more. I'm increasingly starting to think that anything that produces different outputs for the same input is by definition a bug, whether the cause is platform dependent or not.

**Comment by jelmersnoeck** [comment] 2015-10-08 06:43
I'm sorry, I haven't had much time to work on this yet.

I agree though, it should - especially if it's on the same platform where I'm testing - always generate the exact same output. One thing I thought of was maybe that outputting data to a file might be slightly different than outputting it to a buffer. Once I start digging into it more, I'll see what actual file comparison gives.

**Comment by jung-kurt** [comment] 2015-10-08 18:49
I just approached this from a different angle. [This branch](https://github.com/jung-kurt/gofpdf/compare/compare-reference-pdf?expand=1) compares the bytes of an example PDF with those of a reference file. The `/CreationDate` value is effectively ignored by replacing it with a fixed value during the comparison. This makes the process transparent to the PDF generation code as well as the example code.

I have not yet tried comparing reference files with PDFs generated on a different platform or with a different version of the standard library.

**Comment by jelmersnoeck** [comment] 2015-10-09 08:16
I like the way this automatically generates the reference file when the example is run for the first time! That way all the examples immediately start being a reference for the future. (It might be a little bit of a pain when you build the example though)

I am wondering though, we should probably not ignore the reference files? I'm thinking that we want a set of files already there, as an actual reference, which are correct. When someone changes code then, they can see when one of those files has been changed in their git status (or in a pull request).

I'm however not a big fan of the regex replacement for the creation date. It is fine for the core examples, but for external usage (and testing) this might be a bit of a pain. It relies on knowing exactly how the CreationDate is used in the PDF. If this expands - for example when you actually print the creation date on the page - this would not work either.

**Comment by jung-kurt** [comment] 2015-10-09 10:47
> (It might be a little bit of a pain when you build the example though)

Maybe we could address this by treating a zero-length reference file as a match. During development of an example, one could use `touch pdf/reference/foo.pdf` to create, or `cat /dev/null > pdf/reference/foo.pdf` to truncate, the reference file.  Alternatively, I am game to simply having a single command generate them all. Unchanged examples will produce unchanged PDFs, so git won't be given a bunch of spurious changes.

> I am wondering though, we should probably not ignore the reference files? 

You mean in .gitignore? I completely agree -- that was just a temporary directive.

> I'm however not a big fan of the regex replacement for the creation date. It is fine for the core examples, but for external usage (and testing) this might be a bit of a pain. It relies on knowing exactly how the CreationDate is used in the PDF. If this expands - for example when you actually print the creation date on the page - this would not work either.

I'm not sure I understand. This scheme is intended to work only with the example files that gofdpf_test (or test programs beneath `contrib`) produces, and the CreationDate tag is generated by gofpdf itself, so we have complete control over its format. If you're referring to some example using text that matches the expression (for example `/CreationDate (D:20151009064231)`) right in the page content, the matching scheme would still work correctly, and the example PDF would still have the intended contents. Only the reference PDF would have altered contents, but that is acceptable in my opinion.

**Comment by jelmersnoeck** [comment] 2015-10-09 14:25
With external libraries I mean applications using gofpdf internally (so not the core library). Thinking of that again, if we make the regex public, that could help as well.

The idea to do this came out of this instance for me personally, as we produce several PDFs, and being able to test that these do not change trough other criteria would be great.

**Comment by jung-kurt** [comment] 2015-10-09 14:34
Would your purposes be met if gofpdf exported a utility function that simply compares two specified PDFs? That way, the exact methods of comparison would be hidden and could change without breaking the interface.

**Comment by jelmersnoeck** [comment] 2015-10-09 14:55
@jung-kurt if we can export a helper to do that, that'd be great! We can then indeed leave the core library alone and replace both of the CreationDate instances with a fixed date.

**Comment by jung-kurt** [comment] 2015-10-09 14:58
@jelmersnoeck I'll proceed with that approach. One restriction that I will document is that it will be assumed that the specified PDFs were each produced by gofpdf.

**Comment by jelmersnoeck** [comment] 2015-10-09 15:18
Perfect! That makes sense yes.

**Comment by jung-kurt** [comment] 2015-10-09 15:19
How important is it that we identify the actual differences rather than simply report whether the PDFs are equal or not?

**Comment by jelmersnoeck** [comment] 2015-10-09 16:34
I think it could be quit useful to have, especially for subtle differences.

One example (rather simple though) I can think of is font colours. If for some reason it changes slightly from what we expect, we'd like to know. These changes might not always be visible to the eye.

**Comment by jung-kurt** [comment] 2015-10-09 16:39
We can aim for a dump something like `diff` would produce, for example,

    00000230  44 46 20 31 2e 37 29 0a  2f 43 72 65 61 74 69 6f  |DF 1.7)./Creatio|
    00000240  6e 44 61 74 65 20 28 44  3a 32 30 31 35 31 30 30  |nDate (D:2015100|
    00000250  38 31 32 33 30 34 35 29  0a 3e 3e 0a 65 6e 64 6f  |8123045).>>.endo|

This could be potentially noisy in cases where there are a lot of differences, but that should not really happen often.

**Comment by jung-kurt** [comment] 2015-10-09 20:00
I just implemented a rudimentary byte-difference display (see [this branch](https://github.com/jung-kurt/gofpdf/compare/compare-reference-pdf)) and discovered a source of variations within the PDFs generated by gofpdf. Anywhere a map is used, for example with fonts and images, the resulting embedded resource dictionary may vary from run to run. This is embarrassingly obvious in hindsight but evaded me until I wrote the byte-difference routine. The solution will be to wrap all map iterations in a routine that sorts the map keys.

**Comment by stanim** [comment] 2015-10-09 20:14
I come late to the party, but I am really excited about this idea.

I would advise against using a regex. How about exposing a method which can
set manually set the time? If there is no manual time set, time.Now() is
used.

Good idea to sort the map keys, but that should be optional (opt-in for
debugging). Otherwise it might have a unnecessary negative performance
impact on the gofpdf library.

Keep up the good work,

Stani

**Comment by jung-kurt** [comment] 2015-10-09 20:20
> I would advise against using a regex. How about exposing a method which can set manually set the time? If there is no manual time set, time.Now() is used.

Easily done. However, this will require some additional code in the test routines. I'd like to do this without confusing users who are looking to the examples as the easiest way to accomplish a given task. Any ideas?

> Good idea to sort the map keys, but that should be optional (opt-in for debugging). Otherwise it might have a unnecessary negative performance impact on the gofpdf library.

Excellent idea. Again, it would be nice to make this as transparent as possible in the example code.

**Comment by jelmersnoeck** [comment] 2015-10-09 20:30
Interesting regarding the differences with usage of maps. Just to understand this issue, how exactly is the map different from run to run? 

Is the internal state of the map different (so at one point it is in the form of `map[string]int{"key1": 1, "key2": 2}`, another time it is `map[string]int{"key2": 2, "key1": 1}`) or is the way the map is iterated over different?

**Comment by jung-kurt** [comment] 2015-10-09 20:34
> Just to understand this issue, how exactly is the map different from run to run?

From [The Go Programming Language Specification](https://golang.org/ref/spec):

> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.

**Comment by stanim** [comment] 2015-10-09 20:35
It is randomized on purpose:
"When iterating over a map with a range loop, the iteration order is not
specified and is not guaranteed to be the same from one iteration to the
next. *Since Go 1 the runtime randomizes map iteration order*, as
programmers relied on the stable iteration order of the previous
implementation. If you require a stable iteration order you must maintain a
separate data structure that specifies that order."
https://blog.golang.org/go-maps-in-action

**Comment by jelmersnoeck** [comment] 2015-10-09 20:39
Thanks, that clears it up! I'm assuming that will be the differences I've noticed when I did some tests earlier as mentioned [here](https://github.com/matthiasmullie/scrapbook/blob/master/src/Adapters/MemoryStore.php#L94).

**Comment by stanim** [comment] 2015-10-09 20:48
Good point. Just brainstorming ... I see two strategies:

   1. delegate this to the gofpdf library and hide it from the examples: It
   should check if it is run as a test and take appropriate action. As far as
   I know there is no elegant way for the golang to check if code is run as a
   test. So you would have to resort to unwanted tricks like e.g.
   setting/checking env variables,...
   2. add minimal code to the example: My preference would be to define a
   descriptive private method e.g. "markAsTest(f *gofdpf.Fpdf)"
   inside fpdf_test.go It can be extended as needed without adding further
   boilerplate to the examples. As it is a private method it is clear it can
   not be used elsewhere. You could always explain shortly the presence of
   this function somewhere in the documentation. So this approach would only
   add one line to each of the examples.

What do you think?
Stani

**Comment by marcusatbang** [comment] 2015-10-10 23:34
Having a black box comparison function, separate from the tests, is a good idea. It means that the test code itself isn't too convoluted.

I'm not sure I like the idea of generating different PDFs when in test mode. It sounds like it could introduce heisenbugs: things that work differently when you test them than in the real world. Still, I can see how it's the easier solution in this case. You'd want to be able to switch the time-wasteful sorting of map parameters on/off independently of the test mode, to make it easier to identify problems.

The _ideal_ solution would be code that understands the structure of a PDF and can determine whether they're equivalent regardless of being in a different order and using different IDs internally. But that would probably be a great deal of work.

**Comment by jung-kurt** [comment] 2015-10-11 00:24
All good points, @marcusatbang. My [current work branch](https://github.com/jung-kurt/gofpdf/compare/compare-reference-pdf) for this change includes a test-independent comparison function. It introduces two new instance values, a catalog sort flag and fixed creation timestamp. Additionally, the default values of these fields can be set with utility functions before any fpdf instance is created. An `init()` function of the  fpdf_test.go file calls this to set catalog sorting and assigns an arbitrary default creation timestamp. That way, all the example code remains intact. (This is admittedly a questionable practice. Setting default values like this is potentially hazardous because assignments made in different places within a project could interfere with one another in a hard-to-track way. But it addresses the point you made about not binding these features strictly to test-mode.)

Currently, the branch is close to working. The only unit with which I am encountering differences is the template code.

Yes, comparing the semantic parse trees of different documents would be the right way to go about this, but it would be a daunting task.

**Comment by marcusatbang** [comment] 2015-10-11 00:29
What's the issue with the template code? Is it about passing the fixed values into the separate sub-document?

**Comment by jung-kurt** [comment] 2015-10-11 00:32
Non-deterministic map iterations. This will be no big deal to fix, I just haven't gotten to it yet.

**Comment by ajstarks** [comment] 2015-10-11 12:24
Re: sorted maps: would you sort all map operations?  I'm concerned about undue overhead.

**Comment by jung-kurt** [comment] 2015-10-11 12:26
> Re: sorted maps: would you sort all map operations? 

No, only when the resource catalogs are output, and then only when a flag indicates that it should be done.

**Comment by jung-kurt** [comment] 2015-10-13 01:10
I'll close this issue since the discussion has moved over to [Compare example PDFs with reference copies #49](https://github.com/jung-kurt/gofpdf/pull/49).

**Closed by jung-kurt** 2015-10-13 01:10 UTC
